service: book-management-system

provider:
  name: aws
  region: ap-east-1
  stage: production
  memorySize: 512
  timeout: 15

  ecr:
    images:
      appimage:
        path: ./backend
        file: Dockerfile

  environment:
    REMOVE_RUNTIME_STRIP: "false"
    AWS_S3_BUCKET_NAME: ${self:custom.bucketName}
    S3_BUCKET_NAME: ${self:custom.bucketName}
    AWS_REGION: ${self:provider.region}
    MONGO_URI: ${env:MONGO_URI}
    PORT: 5000
    RUNTIME_ENV: AWS
    WS_CONNECTION_TABLE_NAME: ${self:custom.wsConnectionTableName}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - execute-api:ManageConnections
          Resource:
            - "arn:aws:s3:::${self:custom.bucketName}/*"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.wsConnectionTableName}"
            - "arn:aws:execute-api:${self:provider.region}:*:*/${self:provider.stage}/POST/@connections/*"
          

custom:
  bucketName: my-book-system-uploads-${self:provider.stage}
  wsConnectionTableName: websocket-connections-${self:provider.stage}
  apigwBinary:
    types:
      - 'multipart/form-data'

functions:
  api:
    image:
      name: appimage
    reservedConcurrency: 10
    events:
      - httpApi: '*'

  connect:
    handler: ./backend/src/init/connectToDynamoDB/connectToDynamoDB.connectHandler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: ./backend/src/init/connectToDynamoDB/connectToDynamoDB.disconnectHandler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: ./backend/src/init/connectToDynamoDB/connectToDynamoDB.defaultHandler
    events:
      - websocket:
          route: $default

resources:
  Resources:
    BookUploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    WebSocketConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.wsConnectionTableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
