name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    paths-ignore:
      - 'README.md'
      - 'doc/**'
      
jobs:
  deploy-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Configure AWS credentials 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Build and Push Image into ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ts_mern_lms-backend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 4. Update Lambda function code with new image
      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/ts_mern_lms-backend:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend 
    if: ${{ success() }}
    steps:
      - name: Trigger Vercel Deploy
        run: |
         RESPONSE=$(curl -s -X POST -w "%{http_code}" "${{ secrets.VERCEL_DEPLOY_HOOK }}" -o response.json)
          HTTP_CODE=$RESPONSE
          RESPONSE_BODY=$(cat response.json)

          echo "Vercel HTTP Code: $HTTP_CODE"
          echo "Vercel Response: $RESPONSE_BODY"

          if [ "$HTTP_CODE" -eq 201 ] || [ "$HTTP_CODE" -eq 200 ]; then
            echo "Vercel deployment triggered successfully!"
          else
            echo "Error: Vercel API failed with constants $HTTP_CODE"
            exit 1
          fi
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
